import type { Competency } from "./types";

type Lesson = [
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string,
  string[],
];
const lessons: Lesson[] = [
  [
    "T01",
    "Indirect-tax lifecycle and responsibility",
    "Indirect taxes arise in transactions and consumption. Sales tax is usually collected by a seller; use tax can address taxable use when tax was not collected. VAT/GST systems have their own rules and may allow qualifying input-tax recovery. A calculation is only one stage: establish facts, review obligations, configure collection, reconcile, obtain approval, file, pay and preserve evidence. The AM coordinates; specialists interpret law and authorized customers approve financial actions.",
    "A synthetic notice alleges an unpaid period. A return receipt and a payment acceptance are different records; find both before describing resolution.",
    "lifecycle:Linked stages from business facts to retained completion evidence|remittance:Payment to a tax authority|use tax:A consumption-tax obligation investigated when required tax was not collected",
    "Sending a reassuring email completes compliance.",
    "Match a fictional notice to entity, period, filing record and payment record.",
    "Explain a different customer cash-collection issue without promising a legal outcome.",
    "Separate collection, filing and payment; identify the missing evidence; name the authorized owner.",
    "Lifecycle map and issue closure checklist",
    ["sst", "ca-gst"],
  ],
  [
    "T02",
    "Invoices, credits and reconciliation",
    "Track taxable base, tax, gross amount and adjustments separately. Money is represented in integer minor units with explicit currency and rounding. A credit reverses the relevant original transaction amounts; a cash refund is a separate event. Period cutoffs and source-to-ledger differences must be reconciled rather than explained away. Inclusive and exclusive prices require different arithmetic.",
    "Training USD exclusive base 10,000 cents at synthetic 8% yields 800 cents tax and 10,800 gross. Inclusive 12,000 cents at synthetic 20% yields 10,000 base and 2,000 tax.",
    "minor unit:Smallest recorded currency unit, such as cents|credit:Documented adjustment to an invoice|tax payable:Recorded liability to remit tax",
    "Cash received always equals taxable revenue or tax payable.",
    "Reconcile invoices 80,000, tax 6,400 and a credit tax of 800: net tax payable 5,600 cents under stated assumptions.",
    "Create a control-total bridge with a missing credit and a late refund.",
    "Use correct base and sign; show integer rounding; preserve source and period references.",
    "Invoice reconciliation bridge",
    ["training-policy", "ca-gst"],
  ],
  [
    "T03",
    "Investigate nexus and effective dates",
    "Nexus investigation begins with where the business operates and what it sells. Collect entity, employee, inventory and sales facts by location and period. Economic measures can count different transaction classes; a threshold needs its jurisdiction, measurement window and effective date. Finding a sales number is not enough to conclude an obligation. Preserve incomplete history and request the missing records.",
    "Training State Alpha counts synthetic gross sales in a fictional 12-month window; State Beta uses a different exercise definition. Their amounts cannot be combined into a universal test.",
    "nexus:Connection investigated for a jurisdictional tax obligation|measurement window:Defined time period for a threshold|effective date:When a reviewed obligation or change applies",
    "Below an economic threshold means physical presence never matters.",
    "Build a dated map of inventory, staff and channel sales, then ask a precise specialist question.",
    "Assess a new warehouse against incomplete sales history, recording confidence rather than certainty.",
    "Separate physical and economic facts; cite exact period; identify unknown start dates.",
    "Nexus fact matrix",
    ["sst"],
  ],
  [
    "T04",
    "Investigate product and service taxability",
    "A product label rarely contains the full tax fact pattern. Establish what the buyer receives, how it is delivered, contract rights, separate charges, customization and jurisdiction. Software, services, subscriptions, bundles and manufacturing inputs can differ. Use public authority as a research lead; an actual classification needs a qualified reviewer. Never transfer one jurisdiction’s answer to every sale.",
    "A hosted dashboard bundled with analyst consulting needs contract and invoice detail. The game does not assume every service performed with a computer has the same treatment.",
    "taxability:Whether a particular supply is taxable under applicable rules|bundle:Multiple supplies priced together|classification:Mapping a documented supply to a reviewed category",
    "Every subscription is taxable everywhere, or every professional service is exempt everywhere.",
    "Compare a product description with contract rights and separately stated invoice lines.",
    "Write a classification question for a hardware, software and maintenance bundle.",
    "Identify each supply; distinguish confirmed facts from labels; bound proposed configuration pending review.",
    "Product fact sheet and classification decision record",
    ["ny-software", "tx-services"],
  ],
  [
    "T05",
    "Sourcing, addresses and jurisdiction",
    "Sourcing asks which location and jurisdiction matter for the particular transaction. Shipping, billing, use and establishment addresses can serve different purposes. Record which evidence supports the proposed location; flag conflicts and avoid guessing a rate from a ZIP alone. Rate selection follows an approved classification and sourcing decision, with case-period validation.",
    "A software customer pays from one office but has users in several locations. Ask for usage allocation instead of automatically using the billing address.",
    "sourcing:Assigning a transaction to the appropriate location rule|jurisdiction:Authority whose rules must be examined|address evidence:Documented location information relevant to the supply",
    "The server or billing address always determines tax.",
    "Inspect conflicting bill-to, ship-to and actual-use records.",
    "Design an address correction request that preserves the original transaction history.",
    "Use relevant location evidence; expose conflicts; avoid an unsupported rate.",
    "Sourcing evidence log",
    ["ny-software", "sst"],
  ],
  [
    "T06",
    "Resale and exemption evidence",
    "An exemption is a specific claim requiring appropriate facts and evidence. Review purchaser identity, jurisdiction, signature and required details, permitted scope, transaction match and validity for the relevant period. A certificate image is not proof that every purchase is covered. Ask for corrections and use an approved interim treatment rather than silently extending coverage.",
    "A dealer’s resale certificate does not automatically cover items consumed internally. Separate resold parts from office equipment and obtain reviewer approval.",
    "resale:Purchase intended for onward sale|certificate:Document supporting a specific exemption claim|scope:Transactions and uses covered by evidence",
    "A certificate on file makes every sale exempt forever.",
    "Match a certificate to entity, transaction date and stated purchase use.",
    "Resolve a mismatch between certificate entity and acquiring company.",
    "Check completeness and scope; retain evidence; document exception ownership.",
    "Certificate validation matrix",
    ["sst", "ny-software", "training-policy"],
  ],
  [
    "T07",
    "Channels, marketplaces and merchant of record",
    "Channel responsibilities depend on facts and contracts. A marketplace’s collection record may cover specified transactions while the seller retains other obligations. A payment processor is not automatically a merchant of record. Separate direct sales, marketplace settlements, refunds and contractual roles; avoid duplicate tax collection or assuming all sales are handled by another party.",
    "Cedarline’s settlement contains collected tax and marketplace fees; its direct store has separate sales. Reconcile each channel before a return review.",
    "marketplace facilitator:Platform role investigated under jurisdiction rules|merchant of record:Contractual seller role requiring factual confirmation|settlement:Platform payout and adjustments",
    "One marketplace relationship removes every direct-channel obligation.",
    "Read fictional channel contract excerpts and match them to transaction evidence.",
    "Investigate an unknown platform label using contracts and invoice seller identity.",
    "Identify contractual seller; distinguish fees from tax; reconcile channel coverage.",
    "Channel responsibility matrix",
    ["sst", "training-policy"],
  ],
  [
    "T08",
    "Registrations and operational start dates",
    "Registration, collection start, filing frequency, first return, data cutoff and authority to act are separate fields. Confirm the correct legal entity and jurisdiction. A system setting is not a substitute for reviewed effective dates or registration confirmation. Prepare dependencies and approvals before enabling changes, and retain the dated evidence used.",
    "An approved fictional registration date is Day 8; a filing return period includes a different date span. Starting collection only on filing day leaves an operational gap.",
    "registration:Identification of an obligated entity with an authority|filing calendar:Period and due-date schedule|authorization:Permission from the correct decision maker",
    "Collection begins whenever the first return is filed.",
    "Build a timeline from specialist decision through configuration and first filing.",
    "Find a missing approval in a second entity launch plan.",
    "Separate dates; check entity and permissions; assign cutoff and verification owners.",
    "Registration readiness checklist",
    ["sst", "ca-gst"],
  ],
  [
    "T09",
    "Compliance operations and correction trails",
    "Trace a proposed return back to invoices and adjustments through a reconcilable transformation. Check completeness, duplicates, currency, entity mapping and period cutoff. Approval, filing acceptance and payment acceptance are distinct evidence. Correct defective records with an audit trail and retest control totals; preserve the original record. Do not close on a submitted request alone.",
    "A feed repeats one 3,200-cent tax line. Reprocess with a stable transaction key and show that only one instance remains.",
    "control total:Independent amount used to test completeness|idempotency:Repeated operation has no duplicate effect|acceptance:Positive evidence that a filing or payment was received",
    "A green import job proves the return is correct.",
    "Trace source IDs through an import exception report to the draft return.",
    "Create a correction record for a credit in the wrong period.",
    "Reconcile totals; preserve correction history; distinguish submission from acceptance.",
    "Source-to-return reconciliation and acceptance packet",
    ["training-policy", "ca-gst"],
  ],
  [
    "T10",
    "Notices, exposure and specialist remediation",
    "A notice needs entity, period, issue type, amount, response deadline and supporting records. Protect urgent deadlines while verifying facts. Penalties, audits and historical exposure may need tax or legal expertise. The AM gathers evidence, names an owner and communicates what is known; no guaranteed waiver, admission or legal strategy is promised independently.",
    "Two letters have different identifiers: one requests missing information, one alleges an unpaid balance. Avoid assuming a duplicate and deleting one.",
    "notice:Authority communication requiring review|historical exposure:Potential obligations in past periods|remediation:Reviewed steps to correct or resolve a problem",
    "Every notice is a proven debt, or every small notice can wait.",
    "Prepare a notice packet and deadline plan with filing and payment evidence.",
    "Bound an exposure investigation without promising a voluntary-disclosure outcome.",
    "Verify identity and deadline; involve the right expert; maintain customer ownership.",
    "Notice triage packet and response timeline",
    ["sst", "training-policy"],
  ],
  [
    "T11",
    "VAT/GST foundations",
    "VAT/GST investigation separates supplier and customer status, establishment, supply type, place of supply, invoicing, output tax and potentially recoverable input tax. Reverse-charge questions depend on the applicable regime and facts. Do not replace evidence with an email domain or assume every input tax amount is deductible. Synthetic arithmetic teaches the accounting relationship, not eligibility.",
    "Training output tax 24,000 cents less approved qualifying input tax 7,500 cents yields a synthetic net amount of 16,500 cents. Eligibility has already been stated for the exercise.",
    "output tax:Tax on a business’s supplies|input tax:Tax on purchases with recovery subject to rules|reverse charge:Mechanism where a recipient may account for tax under applicable law",
    "A VAT number always proves every purchase is B2B and every expense credit is recoverable.",
    "Record customer status and service facts before considering a place-of-supply rule.",
    "Compare two customers with different establishments and missing evidence.",
    "Separate status from geography; show arithmetic assumptions; request case-specific review.",
    "VAT/GST fact and invoice checklist",
    ["uk-services", "ca-gst"],
  ],
  [
    "T12",
    "International regimes without false equivalence",
    "EU OSS/IOSS, UK VAT and Canada’s GST/HST are different systems. Establish supplier location, goods or services, customer status, transport/import facts and any special regime eligibility. Canada’s provincial systems require separate awareness. A single global registration or platform label does not settle every obligation. Coordinate a jurisdiction-by-jurisdiction launch gate.",
    "Meridian sells digital access; Cedarline ships physical goods. Do not assign both to an import-goods regime merely because both buyers are in the EU.",
    "OSS:EU One Stop Shop schemes with defined scopes|IOSS:Import scheme investigated for qualifying imported goods|GST/HST:Canadian federal goods-and-services and harmonized tax system",
    "EU, UK and Canada are one interchangeable VAT territory.",
    "Compare three jurisdiction fact packets and list separate unanswered questions.",
    "Design an international launch plan that identifies provincial and domestic obligations.",
    "Choose relevant regime questions; avoid copied conclusions; record professional review needs.",
    "International comparison matrix",
    ["eu-oss", "uk-services", "ca-gst"],
  ],
  [
    "A01",
    "Public offering and implementation handoff",
    "Learn the public offering without pretending to know internal tools or policies. After implementation, recover the customer’s agreed scope, entity coverage, configurations, unresolved defects and named owners. The public role provides context for ongoing relationship ownership; it does not grant filing, pricing or payment authority. Every policy in this game is explicitly fictional.",
    "A public site describes managed compliance; a fictional handoff still needs the signed scope and open exception list.",
    "handoff:Transfer of ownership with documented acceptance|service boundary:Agreed included and excluded work|unknown practice:Employer detail not established by public material",
    "Marketing language is a contract or authorization to promise any outcome.",
    "Compare public capability themes with an incomplete fictional handoff.",
    "Create a first-week fact and ownership checklist for a newly transferred account.",
    "Distinguish public claim, fictional policy and unknown practice; verify scope; own open items.",
    "Implementation acceptance and account handoff",
    ["taxwire-public", "taxwire-role", "training-policy"],
  ],
  [
    "A02",
    "Business discovery and research",
    "Research the business model, entities, products, channels, systems, geography and priorities. Label confirmed observations, hypotheses and questions. Use business information to prepare discovery, then ask the customer to validate it. Respect privacy: unrelated personal profiling adds no useful evidence. Ask about changes and decision paths instead of repeating a generic pitch.",
    "A pricing page adds usage billing. Ask when it launched and whether invoice exports include adjustments; do not declare a tax change from the page alone.",
    "hypothesis:Testable explanation awaiting evidence|discovery:Conversation that clarifies customer facts and goals|business model:How value is supplied and revenue is earned",
    "Clicking every public page replaces listening.",
    "Turn three page observations into a short discovery agenda.",
    "Validate a new channel with a systems owner and practitioner.",
    "Label confidence; ask relevant open questions; update the business map after confirmation.",
    "Business model discovery brief",
    ["taxwire-role", "training-policy"],
  ],
  [
    "A03",
    "Stakeholders, authority and preferences",
    "Map sponsor, champion, budget owner, approver, practitioner, technical owner and backup. A helpful champion may lack signature authority. Learn communication preferences through explicit conversation and record them. Use a respectful escalation path that keeps practitioners informed. The map records actual roles and evidence, not assumed personalities.",
    "The accounting contact supplies records; the CFO approves budget; procurement controls contract timing. A renewal plan needs all three.",
    "champion:Person advocating for a solution|approver:Person authorized for a decision|backup:Named person covering absence",
    "The friendliest person can approve every commitment.",
    "Ask who approves changes and who covers leave.",
    "Update a stakeholder map after a sponsor change.",
    "Verify authority; include practitioner and backup; honor stated preferences.",
    "Stakeholder and decision-path map",
    ["taxwire-role", "training-policy"],
  ],
  [
    "A04",
    "Clear and accountable communication",
    "Open with purpose, invite the customer’s priority, listen and summarize before proposing action. Explain facts, uncertainty, impact and next steps in plain language. Difficult updates should be candid without speculation or blame. When you make an error, correct it, describe the impact and take responsibility. Close with named owners and a check-in time.",
    "Instead of “all sorted,” say “the corrected draft reconciles; payment acceptance is pending; Casey owns verification by Day 2 11:00 and I will update you then.”",
    "agenda:Agreed purpose and sequence|closed loop:Verified response to a commitment|uncertainty:Known limit of evidence or conclusion",
    "Confidence means hiding an unresolved risk.",
    "Draft a four-sentence update and compare it with the transparent rubric.",
    "Explain a delay to a second customer and propose a recoverable next step.",
    "State facts without invention; acknowledge impact; name owner and time; avoid guarantees.",
    "Discovery agenda and customer update",
    ["taxwire-role", "training-policy"],
  ],
  [
    "A05",
    "Plan days, weeks and quarters",
    "Plan finite capacity around response deadlines, customer promises and fictional internal targets. These are different obligation types. Include time zones, preparation, specialist queues and buffers. Replan visibly when urgency changes; do not silently abandon an appointment. Close the day with completed evidence and owned carryover. Study and time away are non-punitive.",
    "A specialist slot begins 13:00; a customer update is promised at noon. Reserve the slot and send an interim update before noon.",
    "buffer:Reserved time for variability|commitment:Named owner, deliverable and time|statutory deadline:Legally relevant date needing verified authority",
    "Busy calendars prove good prioritization.",
    "Place three actions in a feasible order with preparation and check-in buffers.",
    "Replan a week after a data defect delays a filing review.",
    "Respect hard deadlines; keep promises owned; identify capacity tradeoffs.",
    "Daily plan and closing review",
    ["training-policy"],
  ],
  [
    "A06",
    "Risk, dependencies and proportionate escalation",
    "Triage by impact, deadline, uncertainty and reversibility. Investigate enough to make a specialist request useful, then involve the right expert when required. Maintain ownership while waiting. Dependencies need input owners, due times and fallback paths. Blanket forwarding consumes scarce capacity and leaves customer communication unmanaged.",
    "A rejected payment needs operations to verify status and an authorized finance approver; a tax specialist reviews any penalty position.",
    "triage:Ordering action by evidence-based urgency|dependency:Input or decision needed before another action|residual work:Owned work still open after a partial outcome",
    "Escalating removes your responsibility.",
    "Prepare a compact packet with facts, unknowns, question and deadline.",
    "Choose between reversible data investigation and a specialist legal question.",
    "Prioritize correctly; bound expert requests; retain update ownership.",
    "Risk and dependency action plan",
    ["training-policy", "taxwire-role"],
  ],
  [
    "A07",
    "Reliable evidence and account records",
    "Record decisions, source IDs, dates, entity, period, owner and confidence. Distinguish evidence from a summary or hearsay. Corrections append to history rather than erase it. A work item is closed only when its acceptance criteria are verified and residual work has a named owner. Notes should let another colleague understand the state without attending every meeting.",
    "A meeting note says “filed”; the register stores its reference, timestamp and receipt, while payment remains pending.",
    "audit trail:Traceable history of records and changes|decision log:Who decided what, when and on which evidence|provenance:Origin of a record or claim",
    "A neatly formatted note is sufficient completion evidence.",
    "Turn informal notes into a decision and evidence log.",
    "Correct an imported record while preserving the original and rationale.",
    "Retain provenance; separate facts from inference; verify closure criteria.",
    "Account record and correction log",
    ["training-policy"],
  ],
  [
    "A08",
    "Customer health and value realization",
    "Health combines observable outcomes, operational reliability, adoption, decision-maker engagement, support burden and commercial risk. Silence and friendliness are weak signals. Record confidence and contradictory evidence. Link claimed value to a baseline and method; improvement can coexist with unresolved compliance risk. A score prompts investigation rather than predicts a person.",
    "A happy practitioner has not invited the budget owner to renewal planning. Trust is improving while commercial uncertainty remains.",
    "health signal:Observation relevant to account risk|value realization:Evidence that a customer outcome improved|confidence:Strength and limits of the assessment",
    "No complaints means the account is healthy.",
    "Compare positive sentiment with defect recurrence and sponsor engagement.",
    "Build an account health explanation from mixed signals.",
    "Use baseline evidence; include contradictions; state uncertainty and next verification.",
    "Evidence-based health review",
    ["taxwire-role", "training-policy"],
  ],
  [
    "A09",
    "Operational and executive reviews",
    "Operational reviews focus on evidence, exceptions and execution decisions; executive reviews connect outcomes, risk and a forward plan. Select audience-appropriate detail while preserving material uncertainty. Do not claim speculative savings as verified value. End with decisions, owners and dates. Customers should be able to challenge the assumptions.",
    "An executive slide shows a reduction from 18 to 9 unresolved mapping defects with period and denominator, alongside an open notice requiring review.",
    "baseline:Comparable starting measurement|outcome:Verified result meaningful to the customer|decision request:Specific approval or direction needed",
    "A long activity list is a strategic review.",
    "Convert ticket counts into an outcome and risk narrative.",
    "Run a review where the CFO disputes the savings estimate.",
    "Use comparable metrics; reveal material risk; request a concrete decision.",
    "Operational review and executive brief",
    ["training-policy", "taxwire-role"],
  ],
  [
    "A10",
    "Renewals, forecasts and commercial authority",
    "Prepare renewals early using scope, verified value, unresolved risk, stakeholder path and procurement timing. Distinguish aspiration from evidence-backed forecast confidence. Negotiation options need authorized commercial approval. Retention metrics require defined denominators and treatment of contraction and expansion. Never promise price, legal relief or service guarantees you cannot approve.",
    "Synthetic opening recurring revenue 100,000; retained 90,000, expansion 15,000 gives NRR 105%, while gross retention is 90% under the stated exercise definition.",
    "NRR:Net recurring revenue retention under a defined cohort method|contraction:Reduction in recurring scope or value|forecast:Evidence-informed estimate, not a promise",
    "A champion’s verbal enthusiasm means a signed renewal.",
    "Identify missing budget approval and procurement milestones.",
    "Draft a forecast range after an executive sponsor departure.",
    "Define metric; assess authority and timing; route offers for approval.",
    "Renewal readiness and forecast record",
    ["taxwire-role", "training-policy"],
  ],
  [
    "A11",
    "Expansion from a real business need",
    "New entities, jurisdictions, products or volumes can create a need for changed scope. Discover the problem and desired outcome before offering anything. Compare no change, scoped support and staged investigation. Declining an unsuitable expansion can preserve trust. Establish fit, dependencies, approval authority and success criteria without pressure or unsupported legal claims.",
    "A customer asks for payroll support; this indirect-tax game’s scope excludes it. Explain the boundary and offer an authorized referral path.",
    "expansion:Agreed increase in appropriate scope|fit:Match between need and supported solution|success criterion:Observable condition for a proposed outcome",
    "Every business change is an immediate upsell.",
    "Qualify a new entity need and identify what evidence remains missing.",
    "Decline a poorly timed expansion while protecting the customer’s priority.",
    "Confirm need; honor scope; compare options; avoid pressure.",
    "Scoped expansion discovery brief",
    ["taxwire-role", "training-policy"],
  ],
  [
    "A12",
    "Improve operations safely",
    "A reusable playbook needs an observable problem, baseline, controlled change, reviewer and outcome measure. Automation can gather and route facts but must not invent approvals or completion evidence. AI is disabled by default; no learner or customer records go to an unapproved model. Product feedback should include reproducible facts and impact while minimizing data.",
    "A duplicate-check pilot reduces review minutes from 45 to 30 with the same defect-detection acceptance test. Sample quality and reviewer sign-off are retained.",
    "playbook:Reusable steps with exceptions and ownership|guardrail:Control that bounds a process|pilot:Limited reversible test before expansion",
    "Automation removes the need for judgment or review.",
    "Write a defect reproduction and a safe pilot acceptance criterion.",
    "Evaluate an AI proposal against confidentiality, authority and fallback requirements.",
    "Measure baseline and result; keep human approval; protect data and provide rollback.",
    "Operational improvement experiment and playbook",
    ["training-policy", "taxwire-role"],
  ],
];

export const competencies: Competency[] = lessons.map((l) => ({
  id: l[0],
  title: l[1],
  explanation: l[2],
  example: l[3],
  glossary: Object.fromEntries(
    l[4].split("|").map((term) => {
      const at = term.indexOf(":");
      return [term.slice(0, at), term.slice(at + 1)];
    }),
  ),
  misconception: l[5],
  guidedPractice: l[6],
  independentPractice: l[7],
  rubric: l[8].split("; ").map((s) => s.replace(/\.$/, "")),
  workProduct: l[9],
  sourceIds: l[10],
}));
